"""Local Windows Excel agent application.

Provides XLSX source reading, snapshot acquisition, change tracking, and sync.
"""

from accounting_local_agent.save_import_coordinator import (
    SAVE_DEBOUNCE_NS,
    SAVE_IMPORT_COORDINATOR_VERSION,
    SaveCoordinatorError,
    SaveCoordinatorPolicyError,
    SaveCoordinatorState,
    SaveCoordinatorStateError,
    SaveCoordinatorView,
    SaveEventKind,
    SaveImportCoordinator,
    SourceReadAttempt,
    SourceReadOutcome,
    read_due_source,
)
from accounting_local_agent.source_watch_runtime import (
    SOURCE_WATCH_RUNTIME_VERSION,
    SourceWatchRuntime,
    SourceWatchRuntimeError,
    SourceWatchRuntimeReason,
    SourceWatchRuntimeState,
    SourceWatchRuntimeView,
)
from accounting_local_agent.xlsx_snapshot_acquisition import (
    DEFAULT_COPY_CHUNK_SIZE,
    XLSX_SNAPSHOT_ACQUISITION_VERSION,
    StableXlsxSnapshot,
    XlsxSnapshotAcquisitionError,
    XlsxSnapshotAcquisitionReason,
    XlsxSnapshotCleanupError,
    XlsxSnapshotIntegrityError,
    XlsxSnapshotStorageError,
    XlsxSourceNotReadyError,
    XlsxSourcePolicyError,
    open_stable_xlsx_snapshot,
)
from accounting_local_agent.xlsx_source_reader import (
    XLSX_SOURCE_READER_VERSION,
    SourceRowLocation,
    XlsxCellError,
    XlsxFormulaCoverageError,
    XlsxHeaderError,
    XlsxIdentityError,
    XlsxPackageError,
    XlsxSourceReadError,
    XlsxSourceReadResult,
    XlsxStructureError,
    read_xlsx_source_snapshot,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_COPY_CHUNK_SIZE",
    "SAVE_DEBOUNCE_NS",
    "SAVE_IMPORT_COORDINATOR_VERSION",
    "SOURCE_WATCH_RUNTIME_VERSION",
    "SaveCoordinatorError",
    "SaveCoordinatorPolicyError",
    "SaveCoordinatorState",
    "SaveCoordinatorStateError",
    "SaveCoordinatorView",
    "SaveEventKind",
    "SaveImportCoordinator",
    "SourceReadAttempt",
    "SourceReadOutcome",
    "SourceRowLocation",
    "SourceWatchRuntime",
    "SourceWatchRuntimeError",
    "SourceWatchRuntimeReason",
    "SourceWatchRuntimeState",
    "SourceWatchRuntimeView",
    "StableXlsxSnapshot",
    "XLSX_SNAPSHOT_ACQUISITION_VERSION",
    "XLSX_SOURCE_READER_VERSION",
    "XlsxCellError",
    "XlsxFormulaCoverageError",
    "XlsxHeaderError",
    "XlsxIdentityError",
    "XlsxPackageError",
    "XlsxSnapshotAcquisitionError",
    "XlsxSnapshotAcquisitionReason",
    "XlsxSnapshotCleanupError",
    "XlsxSnapshotIntegrityError",
    "XlsxSnapshotStorageError",
    "XlsxSourceNotReadyError",
    "XlsxSourcePolicyError",
    "XlsxSourceReadError",
    "XlsxSourceReadResult",
    "XlsxStructureError",
    "open_stable_xlsx_snapshot",
    "read_due_source",
    "read_xlsx_source_snapshot",
]
